REM This still works, Images are in \HiddenCubeDataset\datasets\"directoryname"\images
SET OPENVIBE_MIDDLE=C:\Users\Magna\Dropbox\Research\Tamas\OpenVibe-HiddenCube\
REM python middle.py --name ?? --dimensions ...